spring:
  config:
    activate:
      on-profile: cloud
  cloud:
    gcp:
      credentials:
        location: classpath:solution-challenge-wero-2fc09ab2afef.json

gcs:
  bucketName: wero-gcs-bucket
  publicUrl : https://storage.googleapis.com/wero-gcp-bucket/

